# syntax=docker/dockerfile:1

FROM python:3.9.0

ENV NAMESERVER_PORT "$NAMESERVER_PORT"

WORKDIR /nameserver/

COPY requirements_nameserver.txt requirements_nameserver.txt
RUN pip3 install -r requirements_nameserver.txt
COPY nameserver .
EXPOSE ${NAMESERVER_PORT}

CMD ["sh" , "-c", "python3 -u nameserver.py ${NAMESERVER_PORT} --host=0.0.0.0"]
