# syntax=docker/dockerfile:1

FROM python:3.9.0

ENV STORAGESERVER_HOST "$STORAGESERVER_HOST"
ENV STORAGESERVER_PORT "$STORAGESERVER_PORT"

ENV NAMESERVER_HOST "$NAMESERVER_HOST"
ENV NAMESERVER_PORT "$NAMESERVER_PORT"

ENV REDIS_HOST "$REDIS_HOST"
ENV REDIS_PORT "$REDIS_PORT"

WORKDIR /storageserver/

COPY requirements_storageserver.txt requirements_storageserver.txt
RUN pip3 install -r requirements_storageserver.txt
COPY storageserver .
EXPOSE ${STORAGESERVER_PORT}

CMD ["sh", "-c", "python3 -u storageserver.py ${STORAGESERVER_HOST}:${STORAGESERVER_PORT} ${NAMESERVER_HOST}:${NAMESERVER_PORT} ${REDIS_HOST}:${REDIS_PORT} --host=0.0.0.0"]
