version: "3"
services:
  redis-1:
    image: "redis:alpine"
    command: --port ${REDIS_PORT_1}
    ports:
      - "${REDIS_PORT_1}:${REDIS_PORT_1}"
  storageserver-1:
    build:
      context: ./
      dockerfile: Dockerfile_storageserver
    ports:
      - "${STORAGESERVER_PORT_1}:${STORAGESERVER_PORT_1}"
    environment:
      - STORAGESERVER_PORT=${STORAGESERVER_PORT_1}
      - STORAGESERVER_HOST=${STORAGESERVER_HOST_1}
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
      - REDIS_PORT=${REDIS_PORT_1}
      - REDIS_HOST=${REDIS_HOST_1}

  redis-2:
    image: "redis:alpine"
    command: --port ${REDIS_PORT_2}
    ports:
      - "${REDIS_PORT_2}:${REDIS_PORT_2}"
  storageserver-2:
    build:
      context: ./
      dockerfile: Dockerfile_storageserver
    ports:
      - "${STORAGESERVER_PORT_2}:${STORAGESERVER_PORT_2}"
    environment:
      - STORAGESERVER_PORT=${STORAGESERVER_PORT_2}
      - STORAGESERVER_HOST=${STORAGESERVER_HOST_2}
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
      - REDIS_PORT=${REDIS_PORT_2}
      - REDIS_HOST=${REDIS_HOST_2}

  redis-3:
    image: "redis:alpine"
    command: --port ${REDIS_PORT_3}
    ports:
      - "${REDIS_PORT_3}:${REDIS_PORT_3}"
  storageserver-3:
    build:
      context: ./
      dockerfile: Dockerfile_storageserver
    ports:
      - "${STORAGESERVER_PORT_3}:${STORAGESERVER_PORT_3}"
    environment:
      - STORAGESERVER_PORT=${STORAGESERVER_PORT_3}
      - STORAGESERVER_HOST=${STORAGESERVER_HOST_3}
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
      - REDIS_PORT=${REDIS_PORT_3}
      - REDIS_HOST=${REDIS_HOST_3}
  nameserver:
    build:
      context: ./
      dockerfile: Dockerfile_nameserver
    environment:
      - NAMESERVER_PORT=${NAMESERVER_PORT}
    ports:
      - "${NAMESERVER_PORT}:${NAMESERVER_PORT}"
  client:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile_client
    environment:
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
