version: "3"
services:
  storageserver:
    build:
      context: ./
      dockerfile: Dockerfile_storageserver
    ports:
      - "${STORAGESERVER_PORT_1}:${STORAGESERVER_PORT_1}"
    environment:
      - STORAGESERVER_PORT=${STORAGESERVER_PORT_1}
      - STORAGESERVER_HOST=${STORAGESERVER_HOST_1}
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
      - REDIS_PORT=${REDIS_PORT_1}
      - REDIS_HOST=${REDIS_HOST_1}
  nameserver:
    build:
      context: ./
      dockerfile: Dockerfile_nameserver
    environment:
      - NAMESERVER_PORT=${NAMESERVER_PORT}
    ports:
      - "${NAMESERVER_PORT}:${NAMESERVER_PORT}"
  client:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile_client
    environment:
      - NAMESERVER_PORT=${NAMESERVER_PORT}
      - NAMESERVER_HOST=${NAMESERVER_HOST}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT_1}:${REDIS_PORT_1}"
