# syntax=docker/dockerfile:1

FROM python:3.9.0

ENV NAMESERVER_HOST "$NAMESERVER_HOST"
ENV NAMESERVER_PORT "$NAMESERVER_PORT"

WORKDIR /storageserver/

COPY requirements_storageserver.txt requirements_storageserver.txt
RUN pip3 install -r requirements_storageserver.txt
COPY storageserver .
EXPOSE 18861

CMD ["sh", "-c", "python3 -u storageserver.py $NAMESERVER_HOST $NAMESERVER_PORT --host=0.0.0.0"]
